- name: "Ansible para configurar VM Jenkins"
  hosts: local
  gather_facts: False
  vars_files:
    - vars/aws_credentials.yml
    - vars/aws.yml

  vars:
    name_service: devopers-jenkins

  tasks:
    - name: Launch the new EC2 Instance 22
      ec2_instance:
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"
        name: "{{ name_service }}"
        key_name: "{{ KeyPairDev }}"
        security_group: "{{ security_group }}"
        vpc_subnet_id: "{{ vpc_subnet_ids }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_ami }}"
        network:
            assign_public_ip: true
        state: running
        region: "{{ region }}"
      register: ec2     

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22 
        state: started 
      with_items: "{{ ec2.instances }}"

    - name: Create AWS ECR
      ecs_ecr:
        name: digitalhouse-devops-app
        aws_access_key: "{{ AWS_access_key }}"
        aws_secret_key: "{{ AWS_secret_key }}"                
        region: "{{ region }}" 
      register: ecr   
      
