# file: site.yml
- import_playbook: aws_provisioning_vpc.yml
- import_playbook: aws_provisioning_jenkins.yml
- import_playbook: aws_provisioning_producao.yml
- import_playbook: aws_provisioning_homolog.yml